import Head from "next/head";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store, { useAppSelector } from "../store/store";
import LandingPage from "./home";
import Link from "next/link";
import Navbar from "@/src/components/navbar";
import Login from "./login";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { isLoggedIn } = useAppSelector((state) => state.auth);
  return (
    <Provider store={store}>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>{isLoggedIn}</p>
        <Login />
        <LandingPage />
      </>
    </Provider>
  );
}
